version: "3.3"
services:

  biplus:
    build: .
    image: mchunguzi/mkopo_employer:latest
    container_name: mkopo_employer
    ports:
      - "4040:8080"
      - "4141:4141"
    extra_hosts:
      - "host.docker.internal:host-gateway"



