---
grails:
    profile: web
    codegen:
        defaultPackage: bi.plus
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
server:
    max-http-header-size: 20000
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none

management:
    endpoints:
        jmx:
            unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    username: ${DATABASE_USERNAME:mkononi}
    password: ${DATABASE_PASSWORD:mkononi@oysterbay}

environments:
    development:
        systemLink: http://localhost:8080
        businessCode: 000000
        paymentUrl: https://openapi.m-pesa.com/sandbox/ipg/v2/vodacomTZN/b2cPayment/
        paymentTigoUrl: http://13.245.203.150:8888/t/biplus/b2c/test
        tigoSenderNo: 25565404050
        tigoSenderName: BI PLUS FINANCE LTD
        smsMtandaoUrl: https://messaging-service.co.tz/api/sms/v1/test/text/single
        brandId: 3463
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/db_test?useSSL=false&zeroDateTimeBehavior=convertToNull&MVCC=TRUE&LOCK_TIMEOUT=10000&DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        serverURL: https://biplus.habarisasa.com
        systemLink: http://www.tacip.co.tz:8080/kopafasta
        businessCode: 305358
        paymentUrl: https://openapi.m-pesa.com/openapi/ipg/v2/vodacomTZN/b2cPayment/
        paymentTigoUrl: http://13.245.203.150:8888/t/biplus/b2c/test
        tigoSenderNo: 25566000145
        tigoSenderName: BI PLUS FINANCE LTD
        smsMtandaoUrl: https://messaging-service.co.tz/api/sms/v1/test/text/single
        brandId: 3464
        dataSource:
            dbCreate: update
            url: ${DATABASE_URL:jdbc:mysql://localhost:3306/db_kopa?useSSL=false&zeroDateTimeBehavior=convertToNull&MVCC=TRUE&LOCK_TIMEOUT=10000&DB_CLOSE_ON_EXIT=FALSE&serverTimezone=Africa/Nairobi}
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
